# fly.toml app configuration file generated for relay-server-cool-pine-6226 on 2025-08-08T00:14:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'relay-server-cool-pine-6226'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 3790
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-1x'
